Repository openshift/nmstate-console-plugin, pull requests merged in 2024-09, with the labels that each got.

#49 OCPBUGS-37049: sync upstream/downstream release-4.15
  src/utils/components/PolicyForm/PolicyForm.tsx
  src/utils/components/PolicyForm/PolicyInterface.tsx
  src/views/policies/new/NewPolicy.tsx
  webpack.config.ts
Labels: jira/severity-important, approved, jira/valid-bug, jira/valid-reference, lgtm

#52 CNV-48259: add flag for reference into other plugins
  .gitignore
  cypress/e2e/StatusList.spec.cy.ts
  cypress/support/commands.ts
  cypress/support/selectors.ts
  plugin-manifest.ts
  src/utils/flags/consts.ts
  src/utils/flags/enableNMStateDynamicFlag.ts
  src/utils/flags/index.ts
Labels: approved, jira/valid-reference, lgtm

#53 Pulling form nmstate repo
  .github/workflows/on_pull_request.yaml
  cypress.config.ts
  cypress/e2e/NewPolicy.spec.cy.ts
  deployment/nmstate-console-plugin/Chart.yaml
  locales/en/plugin__nmstate-console-plugin.json
  package.json
  plugin-manifest.ts
  scripts/start-console.sh
  src/console-models/NodeNetworkStateModel.ts
  src/nmstate-types/custom-models/NodeNetworkConfigurationInterface.ts
  src/utils/components/DetailItem/DetailItem.scss
  src/utils/components/DetailItem/DetailItem.tsx
  src/utils/components/DetailItem/DetailItemHeader.tsx
  src/utils/components/DetailItem/EditButton.tsx
  src/utils/components/DetailItem/EditButtonWithTooltip.tsx
  src/utils/components/DetailItem/OwnerDetailItem.tsx
  src/utils/components/MetadataLabels/MetadataLabels.scss
  src/utils/components/MetadataLabels/MetadataLabels.tsx
  src/utils/components/OwnerReferences/OwnerReferences.tsx
  src/utils/components/PolicyForm/PolicyForm.tsx
  src/utils/components/PolicyForm/PolicyFormOVSBridgeMapping.tsx
  src/utils/components/PolicyForm/PolicyFormOVSBridgeMappingExpandable.tsx
  src/utils/components/PolicyForm/PolicyInterface.tsx
  src/utils/components/PolicyForm/PolicyInterfaceExpandable.tsx
  src/utils/components/PolicyForm/constants.ts
  src/utils/components/PolicyForm/utils.ts
  src/utils/components/Toggles/SelectToggle.tsx
  src/views/states/details/StateDetailsPage.tsx
  src/views/states/list/StatesList.tsx
  src/views/states/list/components/InterfaceDrawer/InterfaceDrawer.tsx
  src/views/states/list/constants.ts
  src/views/states/manifest.ts
  src/views/states/topology/Topology.tsx
  src/views/states/topology/components/CustomGroup/CustomGroup.scss
  src/views/states/topology/components/CustomGroup/CustomGroup.tsx
  src/views/states/topology/components/CustomNode/CustomNode.scss
  src/views/states/topology/components/CustomNode/CustomNode.tsx
  src/views/states/topology/components/TopologySidebar/TopologySidebar.scss
  src/views/states/topology/components/TopologySidebar/TopologySidebar.tsx
  src/views/states/topology/components/TopologyToolbar/TopologyToolbar.scss
  src/views/states/topology/components/TopologyToolbar/TopologyToolbar.tsx
  src/views/states/topology/components/TopologyToolbar/TopologyToolbarFilter.tsx
  src/views/states/topology/utils/constants.ts
  src/views/states/topology/utils/factory.ts
  src/views/states/topology/utils/position.ts
  src/views/states/topology/utils/utils.ts
  tsconfig.json
  yarn.lock
Labels: approved, lgtm

#54 Pulling from nmstate repo
  locales/en/plugin__nmstate-console-plugin.json
  src/utils/components/TechPreview/TechPreview.scss
  src/utils/components/TechPreview/TechPreview.tsx
  src/views/states/list/StatesList.tsx
  src/views/states/manifest.ts
  src/views/states/topology/components/BridgeIcon.tsx
  src/views/states/topology/components/TopologyToolbar/TopologyToolbar.tsx
  src/views/states/topology/utils/utils.ts
Labels: approved, lgtm
