Repository openshift/nmstate-console-plugin, pull requests merged in 2025-01, with the labels that each got.

#72 CNV-41967: display nncp configred interfaces
  src/views/states/topology/Topology.tsx
  src/views/states/topology/components/CustomNode/CustomNode.scss
  src/views/states/topology/components/CustomNode/CustomNode.tsx
  src/views/states/topology/utils/utils.ts
Labels: approved, jira/valid-reference, lgtm

#74 start-console script not working unbound variable
  start-console.sh
Labels: approved, lgtm

#76 OCPBUGS-48415: OCPBUGS-45795: OCPBUGS-45880: OCPBUGS-44683: OCPBUGS-44405: fix cves
  package.json
  yarn.lock
Labels: jira/severity-important, approved, jira/valid-bug, jira/valid-reference, lgtm
