Repository openshift/nmstate-console-plugin, pull requests merged in 2025-04, with the labels that each got.

#95 CNV-55191: create policy drawer
  plugin-manifest.ts
  src/utils/components/PolicyForm/PolicyWizard/BasicInfoStep.tsx
  src/utils/components/PolicyForm/PolicyWizard/InterfacesStep.tsx
  src/utils/components/PolicyForm/PolicyWizard/PolicyWizard.tsx
  src/utils/components/PolicyForm/PolicyWizard/policy-wizard.scss
  src/utils/hooks/useQueryParams.ts
  src/views/hostnetworkconfiguration/Topology.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/CreatePolicyDrawer.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/Drawer.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/InterfaceDrawer/InterfaceDrawer.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/TopologySidebar.scss
  src/views/hostnetworkconfiguration/components/TopologySidebar/TopologySidebar.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/constants.ts
  src/views/hostnetworkconfiguration/components/TopologySidebar/hooks/useSelectedID.ts
  src/views/hostnetworkconfiguration/components/TopologySidebar/hooks/useSelectedResources.ts
  src/views/hostnetworkconfiguration/components/TopologyToolbar/TopologyToolbar.tsx
  src/views/policies/details/PolicyDetailsPage.tsx
Labels: approved, jira/valid-reference, lgtm

#96 OCPBUGS-49650: fix topology crash
  src/views/hostnetworkconfiguration/utils/LevelsLayout.ts
  src/views/hostnetworkconfiguration/utils/utils.ts
Labels: approved, jira/valid-bug, jira/valid-reference, lgtm

#99 Fix tests: click skip guided tour
  cypress/e2e/NewPolicy.spec.cy.ts
  cypress/support/selectors.ts
Labels: approved, lgtm

#100 CNV-55191: Show creating policy
  package.json
  src/views/hostnetworkconfiguration/Topology.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/CreatePolicyDrawer.tsx
  src/views/hostnetworkconfiguration/utils/utils.ts
  yarn.lock
Labels: approved, jira/valid-reference, lgtm

#101 CNV-59853: remove various console classes
  src/utils/components/AccessDenied/AccessDenied.tsx
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/utils/components/DetailItem/DetailItem.tsx
  src/utils/components/DetailItem/EditButton.tsx
  src/utils/components/OwnerReferences/OwnerReferences.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/InterfaceDrawer/InterfaceDrawer.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/PolicyDrawer.tsx
  src/views/hostnetworkconfiguration/components/TopologySidebar/TopologySidebar.scss
  src/views/policies/components/DeleteModal.tsx
  src/views/policies/components/EditModal.tsx
  src/views/policies/details/PolicyPageTitle.tsx
  src/views/policies/list/components/PolicyRow.tsx
  src/views/policies/list/hooks/usePolicyColumns.ts
  src/views/states/details/StateDetailsPage.tsx
Labels: approved, jira/valid-reference, lgtm

#102 CNV-59867: fix crash on bridge type change
  src/utils/components/PolicyForm/PolicyWizard/components/BridgeType.tsx
Labels: approved, jira/valid-reference, lgtm

#103 OCPBUGS-55292: avoid empty bridge mapping
  locales/en/plugin__nmstate-console-plugin.json
  src/utils/components/PolicyForm/PolicyWizard/PolicyWizard.tsx
  src/utils/components/PolicyForm/components/PolicyFormOVSBridgeMappingExpandable.tsx
  src/utils/components/PolicyForm/utils.ts
  src/views/policies/components/EditModal.tsx
  src/views/policies/new/NewPolicy.tsx
Labels: jira/severity-critical, approved, jira/valid-bug, jira/valid-reference, lgtm
